# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c7539a17d4166e70d7351fcbcc17fad6"
name = "task6"
handle = "task6"
application_url = "https://lots-include-compare-logos.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "task6-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lots-include-compare-logos.trycloudflare.com/auth/callback",
  "https://lots-include-compare-logos.trycloudflare.com/auth/shopify/callback",
  "https://lots-include-compare-logos.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
